### PR TITLE
Use server time zone when displaying last run

### PR DESCRIPTION
**Pull request by ivanovv**
This PR changes the output of `heartbeat` and `last run` values, they are formatted using current time zone.

### CODE REVIEW

**Comment by ivanovv** [comment]
@ankane ping! :)

**Comment by ankane** [comment]
Hey @ivanovv, thanks for the PR. Can you give an example of the before and after output, as well as remove any style changes from the PR?

**Comment by ankane** [comment]
Hey @ivanovv, saw you remove the style changes, but still not sure I understand how this changes the output. As far as I know, `time_ago_in_words`  shows the relative difference and isn't affected by time zones.

**Comment by ivanovv** [comment]
Hey @ankane, you are right, I think there was some sort of a glitch – when we first started using your gem to check how `clockwork` is doing, I think there was a 1 hour difference (we are in UTC+1 timezone), but now, if I switch to pristine version of this gem I see no changes in output. 

Interestingly, I also don't see anything in Rails commit history that might explain the discrepancy that my commit was intended to fix.

I'm closing the issue as we are switching to pristine version of this gem.

Thanks a lot for your work!!! ❤️

**Comment by ivanovv** [comment]
Hey @ankane, I finally got to the bottom of this and it turned out we are using this gem https://github.com/radar/distance_of_time_in_words which has this issue https://github.com/radar/distance_of_time_in_words/issues/63 :(

```
irb(main):093:0> helper.time_ago_in_words(ClockworkWeb.last_heartbeat)
=> "1 hour and 6 seconds"
irb(main):094:0> helper.time_ago_in_words(ClockworkWeb.last_heartbeat.in_time_zone)
=> "6 seconds"
```

**Comment by ankane** [comment]
That sounds like a tricky one to track down... thanks for the update!

**Pull request closed without merging**
